version: "3"
services:
  # frontend:

  api:
    build: backend
    depends_on:
      - database
    tty: true
    volumes:
      - ./backend/src:/backend/src:cached,ro
    environment:
      API_KEY: 528e3e662b69721285d4d27202af4f4a
    ports:
      - 3001:3001

  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

    ports:
      - 27017:27017
